language: python
python:
    - 2.6
services:
  - redis-server
# command to install dependencies
# # command to run tests
install: true
script:
  - make test python_version=
after_success:
  - make coveralls
notifications:
    email:
        - opensource-tests@paylogic.com
